# Generated by Django 5.2.15 on 2026-06-14 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persisted_secret', models.TextField()),
                ('name', models.CharField(blank=True, max_length=150)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digits', models.PositiveSmallIntegerField(default=6)),
                ('hotp_counter', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='django_mfa__user_id_06b516_idx'), models.Index(fields=['user', 'confirmed_at'], name='django_mfa__user_id_308b64_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hotp_counter__gte', 0)), name='django_mfa_hotp_counter_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persisted_secret', models.TextField()),
                ('name', models.CharField(blank=True, max_length=150)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digits', models.PositiveSmallIntegerField(default=6)),
                ('interval', models.PositiveIntegerField(default=30)),
                ('last_accepted_timecode', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='django_mfa__user_id_1e7cbc_idx'), models.Index(fields=['user', 'confirmed_at'], name='django_mfa__user_id_3081cb_idx')],
            },
        ),
    ]
