# Generated by Django 5.2.15 on 2026-06-15 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mfa_toolkit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("factor", models.CharField(choices=[("hotp", "HOTP")], default="hotp", max_length=16)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("verification", "Verification"),
                            ("resynchronization", "Resynchronization"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "submitted_outcome",
                    models.CharField(choices=[("accepted", "Accepted"), ("rejected", "Rejected")], max_length=16),
                ),
                ("result_classification", models.CharField(max_length=32)),
                ("server_counter", models.PositiveBigIntegerField()),
                ("matched_counter", models.PositiveBigIntegerField(blank=True, null=True)),
                ("next_counter", models.PositiveBigIntegerField()),
                ("look_ahead", models.PositiveIntegerField(blank=True, null=True)),
                ("search_window", models.PositiveIntegerField(blank=True, null=True)),
                ("replay_window", models.PositiveIntegerField()),
                ("submitted_count", models.PositiveIntegerField(blank=True, null=True)),
                ("attempted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="django_mfa_toolkit.hotpdevice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="django_mfa_toolkit_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "attempted_at"], name="django_mfa__user_id_924a9d_idx"),
                    models.Index(fields=["device", "attempted_at"], name="django_mfa__device__4e0d65_idx"),
                    models.Index(
                        fields=["event_type", "result_classification"],
                        name="django_mfa__event_t_65fa86_idx",
                    ),
                    models.Index(fields=["attempted_at"], name="django_mfa__attempt_7f13ed_idx"),
                ],
            },
        ),
    ]
