# Generated by Django 5.2.15 on 2026-06-15 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mfa_toolkit', '0002_mfaauditevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCodeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_mfa_toolkit_recovery_code_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=255)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_mfa_toolkit_recovery_codes', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='django_mfa_toolkit.recoverycodebatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='recoverycodebatch',
            index=models.Index(fields=['user', 'replaced_at'], name='django_mfa__user_id_bb742a_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverycodebatch',
            index=models.Index(fields=['batch_id'], name='django_mfa__batch_i_0e850a_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverycode',
            index=models.Index(fields=['user', 'used_at', 'replaced_at'], name='django_mfa__user_id_c3bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverycode',
            index=models.Index(fields=['batch', 'used_at'], name='django_mfa__batch_i_1a249f_idx'),
        ),
    ]
