# Generated by Django 5.2.15 on 2026-06-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mfa_toolkit', '0003_recoverycodebatch_recoverycode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mfaauditevent',
            name='recovery_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='django_mfa_toolkit.recoverycode'),
        ),
        migrations.AddField(
            model_name='mfaauditevent',
            name='recovery_code_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='django_mfa_toolkit.recoverycodebatch'),
        ),
        migrations.AlterField(
            model_name='mfaauditevent',
            name='event_type',
            field=models.CharField(choices=[('verification', 'Verification'), ('resynchronization', 'Resynchronization'), ('reset', 'Reset')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mfaauditevent',
            name='factor',
            field=models.CharField(choices=[('hotp', 'HOTP'), ('recovery_code', 'Recovery code')], default='hotp', max_length=16),
        ),
        migrations.AlterField(
            model_name='mfaauditevent',
            name='next_counter',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mfaauditevent',
            name='replay_window',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mfaauditevent',
            name='server_counter',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mfaauditevent',
            index=models.Index(fields=['recovery_code_batch', 'attempted_at'], name='django_mfa__recover_783d99_idx'),
        ),
    ]
